function parsePrice(raw) {
  if (raw == null) return null;
  return Number(String(raw).replace(/[$,]/g, ''));
}

function createSlug(name) {
  return name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^\w-]/g, '');
}

/* ---------- CATEGORIES ---------- */

const CDN = "https://muebleria-palito-cdn.b-cdn.net";

export const CATEGORIES = [
  {
    id: "Salas",
    name: "Salas",
    imageUrl: `${CDN}/categorias/salas.jpg`,
    subcategories: ["Grandes", "Medianas", "Pequenas"],
    featured: true,
    productCount: 48,
    displayOrder: 0,
  },
  {
    id: "Comedores",
    name: "Comedores",
    imageUrl: `${CDN}/categorias/comedores.jpg`,
    subcategories: ["4 Puestos", "6 Puestos", "8 Puestos"],
    featured: true,
    productCount: 32,
    displayOrder: 1,
  },
  {
    id: "Dormitorios",
    name: "Dormitorios",
    imageUrl: `${CDN}/categorias/dormitorios.jpg`,
    subcategories: ["1.5 Plz", "2 Plz", "2.5 Plz", "3 Plz"],
    featured: true,
    productCount: 56,
    displayOrder: 2,
  },
  {
    id: "Camas",
    name: "Camas",
    imageUrl: `${CDN}/categorias/camas.jpg`,
    subcategories: ["1.5 Plz", "2 Plz", "2.5 Plz", "3 Plz"],
    featured: true,
    productCount: 44,
    displayOrder: 3,
  },
  {
    id: "Comodas",
    name: "Comodas",
    imageUrl: `${CDN}/categorias/comodas.jpg`,
    subcategories: [],
    featured: false,
    productCount: 18,
    displayOrder: 4,
  },
  {
    id: "Coquetas",
    name: "Coquetas / Peinadoras",
    imageUrl: `${CDN}/categorias/coquetas.jpg`,
    subcategories: [],
    featured: false,
    productCount: 12,
    displayOrder: 5,
  },
  {
    id: "CamaCuna",
    name: "Cama Cuna",
    imageUrl: `${CDN}/categorias/camacuna.jpg`,
    subcategories: [],
    featured: false,
    productCount: 8,
    displayOrder: 6,
  },
  {
    id: "Roperos",
    name: "Roperos",
    imageUrl: `${CDN}/categorias/roperos.jpg`,
    subcategories: [],
    featured: false,
    productCount: 24,
    displayOrder: 7,
  },
  {
    id: "Entretenimiento",
    name: "Centro de Entretenimiento",
    imageUrl: `${CDN}/categorias/entretenimiento.jpg`,
    subcategories: [],
    featured: false,
    productCount: 28,
    displayOrder: 8,
  },
  {
    id: "BasesTv",
    name: "Bases de TV",
    imageUrl: `${CDN}/categorias/basesTv.jpg`,
    subcategories: [],
    featured: false,
    productCount: 15,
    displayOrder: 9,
  },
  {
    id: "Consolas",
    name: "Consolas / Recibidor",
    imageUrl: `${CDN}/categorias/consolas.jpg`,
    subcategories: [],
    featured: false,
    productCount: 11,
    displayOrder: 10,
  },
  {
    id: "Bar",
    name: "Bar",
    imageUrl: `${CDN}/categorias/bar.jpg`,
    subcategories: [],
    featured: false,
    productCount: 19,
    displayOrder: 11,
  },
  {
    id: "Bufetera",
    name: "Bufetera",
    imageUrl: `${CDN}/categorias/bufetera.jpg`,
    subcategories: [],
    featured: false,
    productCount: 9,
    displayOrder: 12,
  },
  {
    id: "Aparador",
    name: "Aparador",
    imageUrl: `${CDN}/categorias/aparador.jpg`,
    subcategories: [],
    featured: false,
    productCount: 14,
    displayOrder: 13,
  },
  {
    id: "Escritorios",
    name: "Escritorios",
    imageUrl: `${CDN}/categorias/escritorios.jpg`,
    subcategories: [],
    featured: false,
    productCount: 22,
    displayOrder: 14,
  },
  {
    id: "SofaCama",
    name: "Sofa Cama",
    imageUrl: `${CDN}/categorias/sofacama.jpg`,
    subcategories: [],
    featured: false,
    productCount: 16,
    displayOrder: 15,
  },
];

/* ---------- PRODUCTS ---------- */

// 9 product images available on Bunny CDN — cycled across all products
const IMGS = [
  `${CDN}/products/cama-platform-oslo.jpg`,
  `${CDN}/products/cama-king-monarch.jpg`,
  `${CDN}/products/set-dormitorio-milano.jpg`,
  `${CDN}/products/colchon-memory-plus.jpg`,
  `${CDN}/products/mesa-noche-flux.jpg`,
  `${CDN}/products/armario-3-puertas.jpg`,
  `${CDN}/products/cabecera-terciopelo-vienna.jpg`,
  `${CDN}/products/cama-tapizada-berlin.jpg`,
  `${CDN}/products/comoda-doble-lund.jpg`,
];
let _imgIdx = 0;
function nextImg() { return IMGS[_imgIdx++ % IMGS.length]; }

// 20 products per category × 16 categories = 320 products; images cycle via nextImg()
const ALL_CATALOG = [

  // ── SALAS (subs: Grandes, Medianas, Pequenas) ──
  { categoryId:"Salas", name:"Sofa Seccional Lineal",        price:1240, originalPrice:1550, featured:true,  isNew:false, sub:null,       description:"Sofa modular en L, tela antimanchas",               colors:["#8b7355","#4a4a4a","#c8bfa8"] },
  { categoryId:"Salas", name:"Reclinable Comfort Pro",       price:890,  originalPrice:null, featured:true,  isNew:false, sub:null,       description:null,                                                 colors:["#2c2c2c","#8b4513"] },
  { categoryId:"Salas", name:"Sofa Chesterfield Classic",    price:1100, originalPrice:1380, featured:false, isNew:false, sub:"Grandes",  description:"Capitone ingles, estructura madera de haya",        colors:["#5c3d1e","#2c2c2c"] },
  { categoryId:"Salas", name:"Sofa Modular Flex 3p",         price:1680, originalPrice:null, featured:false, isNew:true,  sub:"Grandes",  description:"Modular rearrangeable, 7 piezas incluidas",         colors:["#4a4a4a","#c8bfa8"] },
  { categoryId:"Salas", name:"Conjunto Sala Completo",       price:2200, originalPrice:2650, featured:false, isNew:false, sub:"Grandes",  description:"Sofa 3p + 2p + poltrona, tela premium",             colors:["#8b7355","#1a1a18"] },
  { categoryId:"Salas", name:"Sofa Esquinero Mega L",        price:2800, originalPrice:3200, featured:false, isNew:false, sub:"Grandes",  description:"Chaise longue reversible, 3.2m de largo",           colors:["#d4c5b0","#2c2c2c"] },
  { categoryId:"Salas", name:"Sofa Velvet Royal 3p",         price:890,  originalPrice:1100, featured:false, isNew:false, sub:"Medianas", description:"Terciopelo italiano, patas doradas mate",           colors:["#2c2c2c","#4a6741"] },
  { categoryId:"Salas", name:"Sofa 3 Puestos Oslo",          price:760,  originalPrice:null, featured:false, isNew:false, sub:"Medianas", description:"Madera de pino, tapizado en lino natural",          colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Salas", name:"Sofa Minimalista Blanco",      price:980,  originalPrice:null, featured:false, isNew:false, sub:"Medianas", description:"Patas metalicas, tapizado blanco roto",             colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Salas", name:"Sofa Vintage Retro",           price:780,  originalPrice:960,  featured:false, isNew:false, sub:"Medianas", description:"Estilo mid-century, patas palillo nogal",           colors:["#8b7355","#4a6741"] },
  { categoryId:"Salas", name:"Sofa Loveseat Capri 2p",       price:540,  originalPrice:null, featured:false, isNew:true,  sub:"Medianas", description:"2 puestos, tapizado en lino natural",               colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Salas", name:"Poltrona Barcelona",           price:420,  originalPrice:null, featured:false, isNew:false, sub:"Pequenas", description:"Sillon de descanso, estructura madera nogal",       colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Salas", name:"Silla Bergere Clasica",        price:380,  originalPrice:460,  featured:false, isNew:false, sub:"Pequenas", description:"Tapizado en terciopelo, patas torneadas",           colors:["#5c3d1e","#c8bfa8"] },
  { categoryId:"Salas", name:"Puff Otomana Cuero",           price:280,  originalPrice:340,  featured:false, isNew:false, sub:"Pequenas", description:"Cuero genuino, estructura madera solida",           colors:["#5c3d1e","#1a1a18"] },
  { categoryId:"Salas", name:"Poltrona Egg Moderna",         price:560,  originalPrice:680,  featured:false, isNew:true,  sub:"Pequenas", description:"Fibra de vidrio, tapizado desmontable",             colors:["#2c2c2c","#4a6741"] },
  { categoryId:"Salas", name:"Reclinable Masaje Premium",    price:1200, originalPrice:1480, featured:false, isNew:false, sub:null,       description:"4 zonas de masaje, calefaccion lumbar, USB",        colors:["#1a1a18","#5c3d1e"] },
  { categoryId:"Salas", name:"Sofa L Reversible Gris",       price:1560, originalPrice:null, featured:false, isNew:true,  sub:"Grandes",  description:"Chaise longue intercambiable, tela gris perla",     colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Salas", name:"Sofa Cama Auxiliar",           price:580,  originalPrice:720,  featured:false, isNew:false, sub:"Medianas", description:"Doble funcion sala/cama, mecanismo facil",          colors:["#8b7355","#c8bfa8"] },
  { categoryId:"Salas", name:"Poltrona Relax Automatica",    price:780,  originalPrice:940,  featured:false, isNew:false, sub:"Pequenas", description:"Reclinacion electrica, reposapiernas motorizado",   colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Salas", name:"Sofa 2.5 Puestos Linen",      price:640,  originalPrice:null, featured:false, isNew:false, sub:"Medianas", description:"Lino natural, cojines desmontables incluidos",      colors:["#c8bfa8","#8b7355"] },

  // ── COMEDORES (subs: 4 Puestos, 6 Puestos, 8 Puestos) ──
  { categoryId:"Comedores", name:"Mesa Nogal Extensible 6p", price:720,  originalPrice:null, featured:true,  isNew:true,  sub:"6 Puestos", description:"Extensible hasta 2.4m, tapa nogal vaporizado",     colors:["#5c3d1e","#1a1a18"] },
  { categoryId:"Comedores", name:"Comedor Moderno 4p",       price:580,  originalPrice:680,  featured:false, isNew:false, sub:"4 Puestos", description:"Mesa lacada + 4 sillas tapizadas en tela",         colors:["#2c2c2c","#c8bfa8"] },
  { categoryId:"Comedores", name:"Comedor Rustico Roble 8p", price:1450, originalPrice:1750, featured:false, isNew:false, sub:"8 Puestos", description:"Madera solida de roble, estilo granja americano",   colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Comedores", name:"Set Comedor Industrial",   price:860,  originalPrice:null, featured:false, isNew:false, sub:"6 Puestos", description:"Marco metal negro, tablero vidrio templado 12mm",   colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Comedores", name:"Mesa Oval Marfil 4p",      price:490,  originalPrice:590,  featured:false, isNew:true,  sub:"4 Puestos", description:"Acabado marfil mate, patas torneadas lacadas",      colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Comedores", name:"Comedor Glass Premium 6p", price:1200, originalPrice:null, featured:false, isNew:false, sub:"6 Puestos", description:"Vidrio templado 15mm, base acero inoxidable",       colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Comedores", name:"Comedor Redondo 4p",       price:680,  originalPrice:820,  featured:false, isNew:false, sub:"4 Puestos", description:"Mesa circular, ideal espacios reducidos",           colors:["#8b7355","#1a1a18"] },
  { categoryId:"Comedores", name:"Mesa Roble Americano 6p",  price:980,  originalPrice:null, featured:false, isNew:false, sub:"6 Puestos", description:"Roble macizo, herrajes dorados, extensible",        colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Comedores", name:"Comedor Minimalista 4p",   price:740,  originalPrice:null, featured:false, isNew:false, sub:"4 Puestos", description:"Mesa negro mate, sillas tapizado microfibra",       colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"Comedores", name:"Comedor Colonial 8p",      price:1680, originalPrice:2100, featured:false, isNew:false, sub:"8 Puestos", description:"Estilo colonial tallado, madera cedro macizo",      colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Comedores", name:"Mesa Marmol + Sillas 6p",  price:2200, originalPrice:null, featured:true,  isNew:false, sub:"6 Puestos", description:"Marmol Carrara, patas metalicas doradas",           colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Comedores", name:"Comedor Escandinavo 4p",   price:720,  originalPrice:null, featured:false, isNew:false, sub:"4 Puestos", description:"Pino finlandes, sillas con asiento acolchado",      colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Comedores", name:"Mesa Extensible Max 8p",   price:840,  originalPrice:1050, featured:false, isNew:false, sub:"8 Puestos", description:"Extensible 1.6m a 2.8m, laminado nogal",            colors:["#8b7355","#1a1a18"] },
  { categoryId:"Comedores", name:"Comedor Rattan Natural 4p",price:1100, originalPrice:null, featured:false, isNew:true,  sub:"4 Puestos", description:"Rattan tejido a mano, base madera teca",            colors:["#c8bfa8","#5c3d1e"] },
  { categoryId:"Comedores", name:"Mesa Alta Bar/Cocina 4p",  price:420,  originalPrice:null, featured:false, isNew:false, sub:"4 Puestos", description:"Altura 90cm, ideal isla de cocina o bar",           colors:["#1a1a18","#8b7355"] },
  { categoryId:"Comedores", name:"Comedor Madera Pino 4p",   price:480,  originalPrice:580,  featured:false, isNew:false, sub:"4 Puestos", description:"Pino macizo lijado, acabado natural encerado",      colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Comedores", name:"Set Comedor Familiar 8p",  price:1340, originalPrice:1580, featured:false, isNew:false, sub:"8 Puestos", description:"Mesa + 8 sillas con cojin lavable incluido",        colors:["#5c3d1e","#c8bfa8"] },
  { categoryId:"Comedores", name:"Mesa Vidrio Templado 6p",  price:680,  originalPrice:null, featured:false, isNew:false, sub:"6 Puestos", description:"Vidrio esmerilado, estructura metal bronceado",     colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Comedores", name:"Comedor Cafe Estilo 4p",   price:560,  originalPrice:null, featured:false, isNew:false, sub:"4 Puestos", description:"Estilo bistro frances, sillas Thonet incluidas",    colors:["#1a1a18","#5c3d1e"] },
  { categoryId:"Comedores", name:"Set Comedor XL Premium 8p",price:2800, originalPrice:null, featured:false, isNew:false, sub:"8 Puestos", description:"Madera masiva + tapizado cuero genuino, lujo total",colors:["#5c3d1e","#1a1a18"] },

  // ── DORMITORIOS (subs: 1.5 Plz, 2 Plz, 2.5 Plz, 3 Plz) ──
  { categoryId:"Dormitorios", name:"Set Dormitorio Milano",    price:2200, originalPrice:2680, featured:true,  isNew:false, sub:"2 Plz",   description:"Cama + 2 mesas de noche + 2 comodas",              colors:["#8b7355","#c8bfa8"] },
  { categoryId:"Dormitorios", name:"Dormitorio Escandinavo",   price:1650, originalPrice:null, featured:false, isNew:true,  sub:"2.5 Plz", description:"Madera de pino, minimalismo nordico",               colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Dormitorios", name:"Dormitorio Classic King",  price:1980, originalPrice:2400, featured:false, isNew:false, sub:"3 Plz",   description:"Cabecera tapizada, 3 cajones laterales",            colors:["#2c2c2c","#c8bfa8"] },
  { categoryId:"Dormitorios", name:"Set Juvenil Flex",         price:1100, originalPrice:null, featured:false, isNew:false, sub:"1.5 Plz", description:"Cama 1.5 + escritorio + estante modular",          colors:["#4a6741","#d4c5b0"] },
  { categoryId:"Dormitorios", name:"Dormitorio Loft Urban",    price:1420, originalPrice:1680, featured:false, isNew:false, sub:"2 Plz",   description:"Estilo industrial, metal y madera reciclada",       colors:["#1a1a18","#8b7355"] },
  { categoryId:"Dormitorios", name:"Set Dormitorio Paris",     price:2450, originalPrice:null, featured:false, isNew:true,  sub:"3 Plz",   description:"Cabecera capitone, tapizado gris perla",            colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Dormitorios", name:"Dormitorio Industrial",    price:1280, originalPrice:1560, featured:false, isNew:false, sub:"2 Plz",   description:"Metal negro + madera recuperada, look factory",    colors:["#1a1a18","#5c3d1e"] },
  { categoryId:"Dormitorios", name:"Set Completo Roma",        price:3200, originalPrice:null, featured:true,  isNew:false, sub:"3 Plz",   description:"6 piezas, madera nogal premium, herrajes dorados", colors:["#5c3d1e","#c8bfa8"] },
  { categoryId:"Dormitorios", name:"Dormitorio Nordico Blanco",price:1650, originalPrice:1980, featured:false, isNew:false, sub:"2 Plz",   description:"Pino blanco, lineas limpias, ambiente luminoso",   colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Dormitorios", name:"Set Minimalista Tokyo",    price:1880, originalPrice:null, featured:false, isNew:false, sub:"2.5 Plz", description:"Bajo perfil, colores neutros, madera clara",        colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Dormitorios", name:"Dormitorio Vintage Oak",   price:2100, originalPrice:null, featured:false, isNew:false, sub:"3 Plz",   description:"Roble envejecido, tiradores ceramica blanca",       colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Dormitorios", name:"Set Juvenil Colores",      price:980,  originalPrice:1180, featured:false, isNew:false, sub:"1.5 Plz", description:"Lacado en colores vivos, ideal habitacion infantil",colors:["#4a6741","#c8bfa8"] },
  { categoryId:"Dormitorios", name:"Dormitorio Moderno 2p",    price:1450, originalPrice:null, featured:false, isNew:false, sub:"2 Plz",   description:"Cabecera LED integrada, cajones con amortiguador", colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"Dormitorios", name:"Set Completo Versalles",   price:4200, originalPrice:null, featured:false, isNew:false, sub:"3 Plz",   description:"8 piezas, estilo clasico europeo, nogal macizo",   colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Dormitorios", name:"Dormitorio Rustico Pino",  price:1200, originalPrice:1450, featured:false, isNew:false, sub:"2 Plz",   description:"Pino macizo, vetas naturales visibles",             colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Dormitorios", name:"Set Matrimonial Cannes",   price:2650, originalPrice:null, featured:false, isNew:true,  sub:"2.5 Plz", description:"Cabecera tapizada XL + mesa noche flotante",        colors:["#c8bfa8","#4a4a4a"] },
  { categoryId:"Dormitorios", name:"Dormitorio Clasico Blanco",price:1580, originalPrice:null, featured:false, isNew:false, sub:"2 Plz",   description:"Lacado blanco brillante, patas plateadas",          colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Dormitorios", name:"Set Premium Miami",        price:3450, originalPrice:4100, featured:false, isNew:false, sub:"3 Plz",   description:"Estilo contemporaneo, acabados lacados alto brillo",colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Dormitorios", name:"Dormitorio Funcional Max", price:1380, originalPrice:null, featured:false, isNew:false, sub:"1.5 Plz", description:"Cama nido + escritorio + armario integrado",        colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Dormitorios", name:"Set Dormitorio Completo",  price:2900, originalPrice:null, featured:false, isNew:false, sub:"2.5 Plz", description:"5 piezas coordinadas, madera de haya natural",      colors:["#8b7355","#d4c5b0"] },

  // ── CAMAS (subs: 1.5 Plz, 2 Plz, 2.5 Plz, 3 Plz) ──
  { categoryId:"Camas", name:"Cama Platform Oslo",            price:980,  originalPrice:1420, featured:true,  isNew:false, sub:"2 Plz",   description:"Estructura nogal, cabecera tapizada queen",         colors:["#c8bfa8","#4a4a4a"] },
  { categoryId:"Camas", name:"Cama King Monarch",             price:1450, originalPrice:null, featured:false, isNew:true,  sub:"3 Plz",   description:"Diseno imperial, patas torneadas, cabecera alta",  colors:["#2c2c2c","#8b7355","#5c3d1e"] },
  { categoryId:"Camas", name:"Cama Tapizada Berlin",          price:1180, originalPrice:1390, featured:false, isNew:false, sub:"2.5 Plz", description:"Estructura acolchada de lino natural, queen",       colors:["#d4c5b0","#4a4a4a"] },
  { categoryId:"Camas", name:"Colchon Memory Plus",           price:680,  originalPrice:850,  featured:false, isNew:false, sub:null,      description:"Foam viscoelastico, 60 noches de garantia",         colors:[] },
  { categoryId:"Camas", name:"Cama Turca Sofis",              price:640,  originalPrice:780,  featured:false, isNew:false, sub:"1.5 Plz", description:"Base completa turca, ideal sofa-cama diurna",       colors:["#8b7355","#c8bfa8"] },
  { categoryId:"Camas", name:"Cama Carrozza Clasica",         price:1120, originalPrice:null, featured:false, isNew:false, sub:"2 Plz",   description:"Hierro forjado, cabecera y piecera ornamental",     colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Camas", name:"Cama Box Resortes Plus",        price:580,  originalPrice:720,  featured:false, isNew:false, sub:"2 Plz",   description:"Base box + colchon resortes ensacados 200 hilos",  colors:["#4a4a4a","#c8bfa8"] },
  { categoryId:"Camas", name:"Cama Flotante LED",             price:1340, originalPrice:null, featured:false, isNew:true,  sub:"2.5 Plz", description:"Efecto flotante, tira LED perimetral RGB",          colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"Camas", name:"Cama Forjada Artesanal",        price:890,  originalPrice:1100, featured:false, isNew:false, sub:"2 Plz",   description:"Hierro forjado a mano, acabado bronceado envejecido",colors:["#5c3d1e","#4a4a4a"] },
  { categoryId:"Camas", name:"Cama Infantil Tren",            price:420,  originalPrice:520,  featured:false, isNew:false, sub:"1.5 Plz", description:"Forma de locomotora, pintura atoxica certificada",  colors:["#4a6741","#d4c5b0"] },
  { categoryId:"Camas", name:"Cama Dosel Princess",           price:1650, originalPrice:null, featured:true,  isNew:false, sub:"3 Plz",   description:"Dosel completo con cortinas de tul, estructura nogal",colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"Camas", name:"Cama Capitone Lujo",            price:1480, originalPrice:1780, featured:false, isNew:false, sub:"2.5 Plz", description:"Capitone frances, terciopelo importado, base lacada",colors:["#2c2c2c","#5c3d1e"] },
  { categoryId:"Camas", name:"Cama Rustica Pino",             price:560,  originalPrice:null, featured:false, isNew:false, sub:"2 Plz",   description:"Pino macizo con vetas naturales, estilo cabin",     colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Camas", name:"Cama Litera Doble",             price:780,  originalPrice:950,  featured:false, isNew:false, sub:"1.5 Plz", description:"Litera 2 camas, escalera lateral, proteccion",      colors:["#d4c5b0","#4a6741"] },
  { categoryId:"Camas", name:"Cama Storage Ottoman",          price:1200, originalPrice:null, featured:false, isNew:false, sub:"2 Plz",   description:"Base con almacenamiento, apertura hidraulica",      colors:["#4a4a4a","#c8bfa8"] },
  { categoryId:"Camas", name:"Cama Japonesa Tatami",          price:680,  originalPrice:840,  featured:false, isNew:false, sub:"2 Plz",   description:"Perfil ultra bajo, madera clara, tatami incluido",  colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Camas", name:"Cama Queen Hollywood",          price:1380, originalPrice:null, featured:false, isNew:false, sub:"2.5 Plz", description:"Cabecera alta acolchada, look glamour",             colors:["#c8bfa8","#2c2c2c"] },
  { categoryId:"Camas", name:"Base Cama Madera Maciza",       price:420,  originalPrice:null, featured:false, isNew:false, sub:"2 Plz",   description:"Base solida sin colchon, 5 tablas de soporte",      colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Camas", name:"Cama Plataforma Baja",          price:780,  originalPrice:960,  featured:false, isNew:false, sub:"2 Plz",   description:"Perfil bajo 20cm, minimalismo japones",             colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Camas", name:"Cama Premium Bianca",           price:2100, originalPrice:null, featured:false, isNew:true,  sub:"3 Plz",   description:"Lacada blanca piano, cabecera tufted, fierro dorado",colors:["#d4c5b0","#c8bfa8"] },

  // ── COMODAS ──
  { categoryId:"Comodas", name:"Comoda Doble Lund",           price:520,  originalPrice:null, featured:true,  isNew:false, sub:null, description:"6 cajones, guias metalicas, manijas brutas",          colors:["#8b7355","#c8bfa8"] },
  { categoryId:"Comodas", name:"Comoda Vintage Rattan",       price:380,  originalPrice:450,  featured:false, isNew:true,  sub:null, description:"Rattan natural tejido, 4 cajones amplios",            colors:["#c8bfa8","#5c3d1e"] },
  { categoryId:"Comodas", name:"Comoda Laqueada Blanca",      price:480,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Acabado piano blanco, 5 cajones + espejo",            colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Comodas", name:"Comoda Americana Oak",        price:620,  originalPrice:720,  featured:false, isNew:false, sub:null, description:"Roble americano, herrajes dorados importados",        colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Comodas", name:"Comoda Minimalista Dark",     price:290,  originalPrice:null, featured:false, isNew:false, sub:null, description:"MDF negro mate, 3 cajones push-to-open",             colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"Comodas", name:"Comoda 8 Cajones XL",         price:680,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Amplia capacidad, guias telescopicas full extension",  colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Comodas", name:"Comoda Francesa Dorada",      price:540,  originalPrice:650,  featured:false, isNew:false, sub:null, description:"Estilo Luis XV, herrajes dorados, patas cabriole",    colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Comodas", name:"Comoda Rustica Pino",         price:360,  originalPrice:420,  featured:false, isNew:false, sub:null, description:"Pino macizo, terminacion encerada natural",           colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Comodas", name:"Comoda Espejo Central",       price:580,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Cajones laterales + espejo central integrado",        colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Comodas", name:"Comoda Juvenil Color",        price:320,  originalPrice:380,  featured:false, isNew:true,  sub:null, description:"Lacado en 6 colores disponibles, manijas cromadas",   colors:["#4a6741","#d4c5b0"] },
  { categoryId:"Comodas", name:"Comoda Madera Nogal",         price:760,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Nogal natural, 5 cajones, herrajes matte black",      colors:["#5c3d1e","#1a1a18"] },
  { categoryId:"Comodas", name:"Comoda Industrial Metal",     price:440,  originalPrice:520,  featured:false, isNew:false, sub:null, description:"Marco metalico, cajones madera rustica",              colors:["#1a1a18","#8b7355"] },
  { categoryId:"Comodas", name:"Comoda Flotante Moderna",     price:380,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Instalacion en pared, sin patas, look contemporaneo", colors:["#d4c5b0","#4a4a4a"] },
  { categoryId:"Comodas", name:"Comoda Clasica 6 Cajones",    price:520,  originalPrice:640,  featured:false, isNew:false, sub:null, description:"Perfil clasico, bordes redondeados, manijas ovaladas",colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Comodas", name:"Comoda Italiana Premium",     price:840,  originalPrice:1020, featured:true,  isNew:false, sub:null, description:"Chapado en madera italiana, cierre suave en todos",   colors:["#5c3d1e","#d4c5b0"] },
  { categoryId:"Comodas", name:"Comoda Infantil Nube",        price:280,  originalPrice:340,  featured:false, isNew:true,  sub:null, description:"Forma de nube, colores pastel, bordes seguros",       colors:["#c8bfa8","#4a6741"] },
  { categoryId:"Comodas", name:"Comoda Toscana Madera",       price:680,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Tallado artesanal, madera de cerezo italiano",        colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Comodas", name:"Comoda Baja Japones",         price:340,  originalPrice:410,  featured:false, isNew:false, sub:null, description:"Perfil bajo 70cm, estilo tansu japones",              colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Comodas", name:"Comoda Amplia 5 Cajones",     price:460,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Amplia, ideal dormitorio principal, madera MDF",       colors:["#c8bfa8","#4a4a4a"] },
  { categoryId:"Comodas", name:"Comoda Vintage Colonial",     price:620,  originalPrice:760,  featured:false, isNew:false, sub:null, description:"Estilo colonial, herrajes envejecidos, patas torneadas",colors:["#8b7355","#5c3d1e"] },

  // ── COQUETAS / PEINADORAS ──
  { categoryId:"Coquetas", name:"Coqueta Hollywood Espejo",   price:680,  originalPrice:820,  featured:true,  isNew:false, sub:null, description:"Triple espejo, luz LED perimetral regulable",         colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Coquetas", name:"Peinadora Vintage Roble",    price:480,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Espejo ovalado, 3 cajones joyero laterales",          colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Coquetas", name:"Tocador Minimalista",        price:320,  originalPrice:380,  featured:false, isNew:true,  sub:null, description:"Superficie amplia, organizador lateral + taburete",   colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Coquetas", name:"Coqueta Francesa Blanca",    price:540,  originalPrice:640,  featured:false, isNew:false, sub:null, description:"Lacada blanca, herrajes plateados, espejo biselado",  colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Coquetas", name:"Tocador LED Moderno",        price:680,  originalPrice:null, featured:true,  isNew:false, sub:null, description:"Tira LED Hollywood integrada, enchufe USB incluido",  colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Coquetas", name:"Peinadora Espejo Triple",    price:560,  originalPrice:680,  featured:false, isNew:false, sub:null, description:"3 espejos ajustables, 5 cajones, taburete tapizado",  colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Coquetas", name:"Coqueta Barroca Gold",       price:920,  originalPrice:1100, featured:false, isNew:false, sub:null, description:"Detalles dorados, espejo con relieve, talla manual",  colors:["#c8bfa8","#5c3d1e"] },
  { categoryId:"Coquetas", name:"Tocador Escandinavo",        price:380,  originalPrice:450,  featured:false, isNew:false, sub:null, description:"Madera clara, espejo circular, taburete encastrable", colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Coquetas", name:"Coqueta Rustica Pino",       price:280,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Pino natural, espejo ovalado, cajones amplios",       colors:["#d4c5b0","#5c3d1e"] },
  { categoryId:"Coquetas", name:"Peinadora Art Deco",         price:640,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Geometria Art Deco, nogal + metal dorado mate",       colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Coquetas", name:"Tocador Clasico Laca",       price:460,  originalPrice:560,  featured:false, isNew:false, sub:null, description:"Lacado clasico, espejo aumento lateral incluido",     colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"Coquetas", name:"Coqueta Hollywood Pro",      price:840,  originalPrice:null, featured:false, isNew:false, sub:null, description:"14 bombillas LED, espejo panoramico 120cm",           colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Coquetas", name:"Peinadora Vintage Teka",     price:520,  originalPrice:620,  featured:false, isNew:false, sub:null, description:"Madera de teka reciclada, patina natural envejecida", colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Coquetas", name:"Tocador Infantil Color",     price:240,  originalPrice:290,  featured:false, isNew:true,  sub:null, description:"Colores pastel, espejo irrompible, cajones seguros",  colors:["#4a6741","#c8bfa8"] },
  { categoryId:"Coquetas", name:"Coqueta Espejo Oval",        price:480,  originalPrice:580,  featured:false, isNew:false, sub:null, description:"Espejo ovalado 80x60, 4 cajones madera clara",       colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Coquetas", name:"Peinadora Colonial",         price:560,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Estilo colonial tallado, madera cedro importado",     colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Coquetas", name:"Tocador Flotante",           price:320,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Montaje en pared, sin patas, espejo ovalado",         colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Coquetas", name:"Coqueta Paris Elite",        price:780,  originalPrice:940,  featured:false, isNew:false, sub:null, description:"Estilo parisiense, cuero blanco, dorados inoxidables",colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Coquetas", name:"Peinadora Madera Cedro",     price:440,  originalPrice:530,  featured:false, isNew:false, sub:null, description:"Cedro fragante, cajones con forro textil",            colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Coquetas", name:"Tocador Premium Blanco",     price:620,  originalPrice:740,  featured:false, isNew:false, sub:null, description:"Lacado blanco alto brillo, espejo biselado 70x90",   colors:["#d4c5b0","#c8bfa8"] },

  // ── CAMA CUNA ──
  { categoryId:"CamaCuna", name:"Cuna Convertible Milano",    price:480,  originalPrice:580,  featured:true,  isNew:false, sub:null, description:"Crece con el bebe: cuna, cama junior, sofa",         colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"CamaCuna", name:"Cama Cuna Clasica Roble",    price:320,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Madera solida de roble, varillas de seguridad",       colors:["#8b7355","#d4c5b0"] },
  { categoryId:"CamaCuna", name:"Moises Premium Textil",      price:240,  originalPrice:290,  featured:false, isNew:false, sub:null, description:"Estructura ratan, textil lavable, ruedas con freno",  colors:["#c8bfa8","#5c3d1e"] },
  { categoryId:"CamaCuna", name:"Cuna Funcional 3 en 1",      price:560,  originalPrice:680,  featured:false, isNew:false, sub:null, description:"3 alturas regulables, convierte a cama junior",       colors:["#d4c5b0","#4a6741"] },
  { categoryId:"CamaCuna", name:"Cuna Bambu Natural",         price:380,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Bambu sostenible, acabado natural, respetuoso bebe",  colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"CamaCuna", name:"Cuna Baranda Movil",         price:420,  originalPrice:510,  featured:false, isNew:true,  sub:null, description:"Baranda lateral abatible, acceso facil de noche",     colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"CamaCuna", name:"Cama Cuna Viaje Portatil",   price:180,  originalPrice:220,  featured:false, isNew:false, sub:null, description:"Plegable, bolso transporte incluido, certificada",    colors:["#c8bfa8","#4a6741"] },
  { categoryId:"CamaCuna", name:"Cuna Dosel Princesa",        price:640,  originalPrice:780,  featured:true,  isNew:false, sub:null, description:"Dosel con tul organico, estructura madera blanca",    colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"CamaCuna", name:"Cama Cuna Madera Maciza",    price:480,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Pino macizo FSC, colchon base incluido",              colors:["#d4c5b0","#8b7355"] },
  { categoryId:"CamaCuna", name:"Cuna Moderna Blanca",        price:360,  originalPrice:430,  featured:false, isNew:false, sub:null, description:"MDF lacado, lineas limpias, base regulable 3 pos",    colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"CamaCuna", name:"Cuna Americana Classic",     price:290,  originalPrice:350,  featured:false, isNew:false, sub:null, description:"Estilo americano, baranda fija, muy estable",         colors:["#8b7355","#d4c5b0"] },
  { categoryId:"CamaCuna", name:"Cama Cuna Toddler Plus",     price:520,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Para bebes y ninos hasta 5 anos, segura y durable",   colors:["#4a6741","#d4c5b0"] },
  { categoryId:"CamaCuna", name:"Cuna Ratan Tejido",          price:340,  originalPrice:410,  featured:false, isNew:true,  sub:null, description:"Ratan tejido a mano, aspecto boho, con ruedas",       colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"CamaCuna", name:"Cama Cuna Plegable",         price:220,  originalPrice:270,  featured:false, isNew:false, sub:null, description:"Compacta, se pliega en segundos, viajes y abuelos",   colors:["#d4c5b0","#4a6741"] },
  { categoryId:"CamaCuna", name:"Cuna Convertible 5 Posiciones",price:680,originalPrice:820,  featured:false, isNew:false, sub:null, description:"5 configuraciones hasta cama adolescente",            colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"CamaCuna", name:"Cama Junior Transicion",     price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Transicion cuna-cama, barandas seguridad laterales",  colors:["#d4c5b0","#4a6741"] },
  { categoryId:"CamaCuna", name:"Cuna Loft Madera",           price:440,  originalPrice:530,  featured:false, isNew:false, sub:null, description:"Diseno loft moderno, madera pino sueco",              colors:["#d4c5b0","#8b7355"] },
  { categoryId:"CamaCuna", name:"Cuna Pintada a Mano",        price:560,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Ilustraciones artesanales, pintura atoxica certificada",colors:["#c8bfa8","#4a6741"] },
  { categoryId:"CamaCuna", name:"Cuna Tipo Moises Madera",    price:290,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Madera haya, mecedor opcional, base solida",          colors:["#d4c5b0","#8b7355"] },
  { categoryId:"CamaCuna", name:"Cuna Ecologica Certificada", price:420,  originalPrice:510,  featured:false, isNew:true,  sub:null, description:"Maderas FSC, pinturas base agua, 0% toxicos",         colors:["#4a6741","#d4c5b0"] },

  // ── ROPEROS ──
  { categoryId:"Roperos", name:"Armario 3 Puertas Espejo",    price:890,  originalPrice:null, featured:true,  isNew:false, sub:null, description:"Espejo de cuerpo entero, organizacion interior",       colors:["#c8bfa8","#2c2c2c"] },
  { categoryId:"Roperos", name:"Ropero Esquinero Premium",    price:1240, originalPrice:1480, featured:false, isNew:false, sub:null, description:"Maximo aprovechamiento de esquina, 6 puertas",         colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Roperos", name:"Vestidor Modular Walk-in",    price:2100, originalPrice:2500, featured:false, isNew:true,  sub:null, description:"Sistema modular personalizable 100%",                  colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Roperos", name:"Armario Japones Shoji",       price:760,  originalPrice:900,  featured:false, isNew:false, sub:null, description:"Puertas deslizantes shoji, interior organizado",       colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Roperos", name:"Ropero Infantil Color",       price:480,  originalPrice:null, featured:false, isNew:false, sub:null, description:"MDF lacado, colores pasteles, 4 puertas",              colors:["#4a6741","#c8bfa8"] },
  { categoryId:"Roperos", name:"Armario 4 Puertas Clasico",   price:1080, originalPrice:1320, featured:false, isNew:false, sub:null, description:"Madera maciza, interior con cajones y barra",          colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Roperos", name:"Ropero Corredera Moderna",    price:980,  originalPrice:1180, featured:false, isNew:false, sub:null, description:"Puertas correderas 2.2m alto, espejo central",         colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Roperos", name:"Armario Rustico Pino",        price:640,  originalPrice:780,  featured:false, isNew:false, sub:null, description:"Pino macizo envejecido, bisagras forjadas",            colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Roperos", name:"Ropero Italiano Premium",     price:1680, originalPrice:null, featured:true,  isNew:false, sub:null, description:"Chapa nogal italiano, sistema push-open",              colors:["#5c3d1e","#d4c5b0"] },
  { categoryId:"Roperos", name:"Armario Blanco Laqueado",     price:820,  originalPrice:1020, featured:false, isNew:false, sub:null, description:"Lacado blanco piano, interior regulable",              colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Roperos", name:"Ropero Escandinavo Oak",      price:1100, originalPrice:null, featured:false, isNew:false, sub:null, description:"Roble escandinavo, patas de madera, aspecto limpio",   colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Roperos", name:"Armario Madera Nogal",        price:1380, originalPrice:1680, featured:false, isNew:true,  sub:null, description:"Nogal americano, interior con espejo y cajones",       colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Roperos", name:"Ropero Colonial Tallado",     price:1240, originalPrice:null, featured:false, isNew:false, sub:null, description:"Tallado artesanal colonial, madera cedro macizo",      colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Roperos", name:"Armario Minimalista Negro",   price:780,  originalPrice:940,  featured:false, isNew:false, sub:null, description:"Negro mate, tirador oculto, interior blanco",          colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Roperos", name:"Ropero Modular Sistema",      price:1540, originalPrice:1840, featured:false, isNew:false, sub:null, description:"Configurable en L o lineal, 180-360cm ancho",         colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Roperos", name:"Armario 2 Puertas Junior",    price:480,  originalPrice:580,  featured:false, isNew:false, sub:null, description:"Juvenil, barra regulable en altura, cajones",          colors:["#d4c5b0","#4a6741"] },
  { categoryId:"Roperos", name:"Ropero Esquinero Max",        price:1680, originalPrice:2000, featured:false, isNew:false, sub:null, description:"Ideal esquinas, 8 puertas, maxima capacidad",          colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Roperos", name:"Armario Industrial Metal",    price:920,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Marco metalico, puertas madera rustica, look loft",    colors:["#1a1a18","#8b7355"] },
  { categoryId:"Roperos", name:"Ropero Clasico 6 Puertas",    price:1480, originalPrice:1780, featured:false, isNew:false, sub:null, description:"6 puertas, espejo central, cajoneras internas",        colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Roperos", name:"Armario Multifuncional",      price:860,  originalPrice:1040, featured:false, isNew:true,  sub:null, description:"Ropero + escritorio + estante integrado en 1 modulo", colors:["#d4c5b0","#1a1a18"] },

  // ── ENTRETENIMIENTO ──
  { categoryId:"Entretenimiento", name:"Centro Entret. Madeira",  price:680,  originalPrice:820,  featured:true,  isNew:false, sub:null, description:"Mueble TV hasta 75in, nichos flotantes laterales", colors:["#5c3d1e","#1a1a18"] },
  { categoryId:"Entretenimiento", name:"Rack TV Minimalista",      price:320,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Madera flotante, cable management integrado",       colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Entretenimiento", name:"Biblioteca Modular 5p",    price:540,  originalPrice:640,  featured:false, isNew:false, sub:null, description:"5 modulos apilables, estilo escandinavo, pino",     colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Entretenimiento", name:"Centro TV Industrial",     price:760,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Metal y madera reciclada, 2 puertas abatibles",     colors:["#1a1a18","#5c3d1e"] },
  { categoryId:"Entretenimiento", name:"Mueble Multimedia Oslo",   price:890,  originalPrice:1080, featured:false, isNew:false, sub:null, description:"Riel LED integrado, 4 cajones con guia metalica",   colors:["#2c2c2c","#c8bfa8"] },
  { categoryId:"Entretenimiento", name:"Rack Flotante Roble",      price:380,  originalPrice:460,  featured:false, isNew:true,  sub:null, description:"Instalacion en pared, chapa de roble natural",      colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Entretenimiento", name:"Centro Entretenimiento XL",price:1120, originalPrice:null, featured:true,  isNew:false, sub:null, description:"2.4m ancho, TV + vinilo + consolas todo organizado", colors:["#1a1a18","#8b7355"] },
  { categoryId:"Entretenimiento", name:"Mueble TV Escandinavo",    price:560,  originalPrice:680,  featured:false, isNew:false, sub:null, description:"Patas palillo, puertas ratán, estilo hygge",         colors:["#d4c5b0","#5c3d1e"] },
  { categoryId:"Entretenimiento", name:"Rack TV con Cajones",      price:480,  originalPrice:null, featured:false, isNew:false, sub:null, description:"4 cajones + barra para consolas, madera MDF",        colors:["#8b7355","#1a1a18"] },
  { categoryId:"Entretenimiento", name:"Centro AV Premium",        price:1340, originalPrice:1580, featured:true,  isNew:false, sub:null, description:"Gestion de cables integrada, iluminacion LED",      colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Entretenimiento", name:"Mueble Biblioteca Total",  price:840,  originalPrice:1020, featured:false, isNew:false, sub:null, description:"Piso a techo, 3m alto, escalera incluida",           colors:["#5c3d1e","#d4c5b0"] },
  { categoryId:"Entretenimiento", name:"Rack Vintage Industrial",  price:560,  originalPrice:680,  featured:false, isNew:false, sub:null, description:"Tuberia metalica + tableros madera recuperada",      colors:["#1a1a18","#8b7355"] },
  { categoryId:"Entretenimiento", name:"Centro TV Minimalista",    price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Perfil bajo 35cm, largo 180cm, lacado blanco",       colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Entretenimiento", name:"Mueble TV Madera Solida",  price:720,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Madera maciza, bisagras amortiguadas, 3 puertas",    colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Entretenimiento", name:"Rack Modular Extensible",  price:680,  originalPrice:820,  featured:false, isNew:true,  sub:null, description:"Crece con tu coleccion, modulos de 40cm",           colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Entretenimiento", name:"Centro Entretenimiento Loft",price:940,originalPrice:1120, featured:false, isNew:false, sub:null, description:"Estilo loft urbano, metal + madera, pies metalicos", colors:["#1a1a18","#5c3d1e"] },
  { categoryId:"Entretenimiento", name:"Mueble TV con Barra",      price:620,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Barra de led inferior, ideal sala de cine en casa",  colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Entretenimiento", name:"Rack TV Flotante LED",     price:540,  originalPrice:660,  featured:false, isNew:false, sub:null, description:"Montaje en pared, LED ambiental trasero",            colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"Entretenimiento", name:"Biblioteca Nogal Clasica", price:780,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Nogal natural, estantes regulables, molduras",       colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Entretenimiento", name:"Centro Multimedia Max",    price:1080, originalPrice:1280, featured:false, isNew:false, sub:null, description:"Maximo 3m ancho, incluye modulo esquinero",          colors:["#1a1a18","#8b7355"] },

  // ── BASES TV ──
  { categoryId:"BasesTv", name:"Base TV Giratoria 55in",      price:180,  originalPrice:220,  featured:false, isNew:false, sub:null, description:"Giro 360 grados, compatible VESA 200x200",            colors:["#1a1a18"] },
  { categoryId:"BasesTv", name:"Soporte TV Flotante 65in",    price:140,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Instalacion en pared, canaleta cable oculto",         colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"BasesTv", name:"Mesa TV con Ruedas",          price:220,  originalPrice:280,  featured:false, isNew:false, sub:null, description:"Movil, 2 repisas, soporta hasta 50kg",                colors:["#1a1a18","#8b7355"] },
  { categoryId:"BasesTv", name:"Pedestal TV Madera Nogal",    price:290,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Pedestal nogal, estable para TV hasta 85in",          colors:["#5c3d1e","#c8bfa8"] },
  { categoryId:"BasesTv", name:"Base TV Universal 75in",      price:160,  originalPrice:200,  featured:false, isNew:false, sub:null, description:"Compatible con casi todos los modelos VESA",          colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"BasesTv", name:"Soporte TV Articulado",       price:120,  originalPrice:150,  featured:false, isNew:false, sub:null, description:"Brazo articulado, inclinacion y giro total",          colors:["#1a1a18"] },
  { categoryId:"BasesTv", name:"Mesa TV Industrial Metal",    price:240,  originalPrice:290,  featured:false, isNew:false, sub:null, description:"Estructura metalica, repisa madera, ruedas bloqueo",  colors:["#1a1a18","#8b7355"] },
  { categoryId:"BasesTv", name:"Base TV Esquinera 55in",      price:180,  originalPrice:220,  featured:false, isNew:true,  sub:null, description:"Ideal para esquinas, giro 90 grados",                 colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"BasesTv", name:"Soporte TV Techo",            price:200,  originalPrice:240,  featured:false, isNew:false, sub:null, description:"Instalacion en techo, cable integrado, nivelar",      colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"BasesTv", name:"Mesa TV Rustica Madera",      price:260,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Pino macizo, 2 repisas, estilo cottage",              colors:["#d4c5b0","#8b7355"] },
  { categoryId:"BasesTv", name:"Base TV Doble Brazo",         price:240,  originalPrice:290,  featured:false, isNew:false, sub:null, description:"Dos brazos independientes, para TVs duales",          colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"BasesTv", name:"Pedestal TV Negro Mate",      price:160,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Negro mate, base amplia antivuelco, 55-85in",         colors:["#1a1a18"] },
  { categoryId:"BasesTv", name:"Soporte TV Extensible",       price:180,  originalPrice:220,  featured:false, isNew:false, sub:null, description:"Longitud del brazo ajustable 30-50cm",                colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"BasesTv", name:"Mesa TV con Gaveta",          price:300,  originalPrice:360,  featured:false, isNew:true,  sub:null, description:"1 gaveta + repisa inferior, ruedas silenciosas",      colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"BasesTv", name:"Base TV Giratoria 85in",      price:320,  originalPrice:380,  featured:false, isNew:false, sub:null, description:"Para TV grandes, base de aluminio fundido",           colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"BasesTv", name:"Soporte TV Minimalista",      price:100,  originalPrice:130,  featured:false, isNew:false, sub:null, description:"Perfil ultra delgado, fijo en pared, carga 35kg",     colors:["#1a1a18"] },
  { categoryId:"BasesTv", name:"Mesa TV Flotante Madera",     price:220,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Madera flotante en pared, 120cm, sin patas",          colors:["#d4c5b0","#8b7355"] },
  { categoryId:"BasesTv", name:"Base TV VESA Premium",        price:280,  originalPrice:340,  featured:false, isNew:false, sub:null, description:"Compatible VESA universal, nivelacion precision",     colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"BasesTv", name:"Soporte TV Portatil",         price:90,   originalPrice:120,  featured:false, isNew:true,  sub:null, description:"Portatil, sin perforar pared, base plegable",         colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"BasesTv", name:"Mesa TV Madera Maciza",       price:340,  originalPrice:410,  featured:false, isNew:false, sub:null, description:"Madera maciza con talla, estilo clasico atemporal",   colors:["#8b7355","#5c3d1e"] },

  // ── CONSOLAS / RECIBIDOR ──
  { categoryId:"Consolas", name:"Consola Recibidor Marmol",   price:480,  originalPrice:580,  featured:true,  isNew:false, sub:null, description:"Tapa marmol italiano, patas doradas forjadas",        colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"Consolas", name:"Aparador Recibidor Slim",    price:340,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Perfil bajo, 2 cajones, espejo redondo incluido",     colors:["#1a1a18","#8b7355"] },
  { categoryId:"Consolas", name:"Recibidor Vintage Madera",   price:280,  originalPrice:320,  featured:false, isNew:false, sub:null, description:"Pino macizo, gancho + cajones + repisa",              colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Consolas", name:"Consola Minimalista Roble",  price:520,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Chapa de roble, tiradores ocultos push-open",         colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Consolas", name:"Aparador Metalico Gold",     price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Marco metal dorado, 3 cajones, espejo ovalado",       colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Consolas", name:"Consola Espejo Dorado",      price:560,  originalPrice:680,  featured:true,  isNew:false, sub:null, description:"Espejo de cuerpo 180cm integrado, marco dorado",      colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Consolas", name:"Recibidor Moderno LED",      price:420,  originalPrice:510,  featured:false, isNew:true,  sub:null, description:"Led inferior ambiental, cajones con suavizado",       colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Consolas", name:"Consola Rustica Hierro",     price:340,  originalPrice:410,  featured:false, isNew:false, sub:null, description:"Hierro forjado + madera maciza, estilo hacienda",     colors:["#1a1a18","#8b7355"] },
  { categoryId:"Consolas", name:"Aparador Clasico Marmol",    price:640,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Tapa marmol negro, cajones forrados en terciopelo",   colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Consolas", name:"Consola Estrecha 80cm",      price:260,  originalPrice:320,  featured:false, isNew:false, sub:null, description:"Solo 28cm de fondo, ideal pasillos estrechos",        colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Consolas", name:"Recibidor Industrial",       price:380,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Tubo negro + tablon madera, estilo loft urbano",      colors:["#1a1a18","#8b7355"] },
  { categoryId:"Consolas", name:"Consola Art Deco Metal",     price:520,  originalPrice:630,  featured:false, isNew:true,  sub:null, description:"Geometria dorada, tablero vidrio, diseno singular",   colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"Consolas", name:"Aparador Nordico Madera",    price:440,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Madera clara, patas finas, cajones suaves",           colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Consolas", name:"Consola Lacada Blanca",      price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Lacado blanco mate, lineas rectas, 2 cajones",        colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Consolas", name:"Recibidor Vintage Colonial", price:560,  originalPrice:680,  featured:false, isNew:false, sub:null, description:"Estilo colonial tallado, madera cedro, 3 gavetas",    colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Consolas", name:"Consola Semicircular",       price:480,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Semicircular, ideal entrada pequeña, con cajones",    colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Consolas", name:"Aparador Bajo Moderno",      price:340,  originalPrice:410,  featured:false, isNew:false, sub:null, description:"Bajo perfil 35cm, 3 puertas, lacado gris",            colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Consolas", name:"Consola Premium Marmol",     price:780,  originalPrice:940,  featured:false, isNew:false, sub:null, description:"Marmol Calacatta, estructura bronce, diseno lujo",    colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Consolas", name:"Recibidor Compacto",         price:220,  originalPrice:280,  featured:false, isNew:false, sub:null, description:"Pequeno, funcional, colgador + cajones + repisa",     colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Consolas", name:"Consola Vintage Madera",     price:460,  originalPrice:560,  featured:false, isNew:true,  sub:null, description:"Madera reciclada vintage, herrajes hierro forjado",   colors:["#8b7355","#5c3d1e"] },

  // ── BAR ──
  { categoryId:"Bar", name:"Mueble Bar Roble Gold",           price:640,  originalPrice:780,  featured:true,  isNew:false, sub:null, description:"Interior espejado, 3 repisas de vidrio, LED",         colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Bar", name:"Bar Giratorio 360",               price:480,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Rueda y abre para acceder, capacidad 20 botellas",    colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Bar", name:"Cantinero Esquinero",             price:720,  originalPrice:860,  featured:false, isNew:false, sub:null, description:"Esquina viva, vinoteca + bar en uno",                 colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Bar", name:"Bar Vintage Industrial",          price:390,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Marco metal + cajon madera rustica, aspecto fabrica", colors:["#1a1a18","#5c3d1e"] },
  { categoryId:"Bar", name:"Vinoteca Bar Premium",            price:1100, originalPrice:1350, featured:false, isNew:false, sub:null, description:"48 botellas, controlador temperatura, compresor",     colors:["#2c2c2c","#c8bfa8"] },
  { categoryId:"Bar", name:"Mueble Bar Nogal Oscuro",         price:680,  originalPrice:820,  featured:false, isNew:false, sub:null, description:"Nogal oscuro, bisagras silenciosas, fondo espejado",  colors:["#5c3d1e","#1a1a18"] },
  { categoryId:"Bar", name:"Cantinero Art Deco",              price:840,  originalPrice:null, featured:true,  isNew:false, sub:null, description:"Geometria dorada Art Deco, mueble escultorial",       colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Bar", name:"Bar Madera Rustico",              price:420,  originalPrice:510,  featured:false, isNew:false, sub:null, description:"Madera reciclada, herrajes de hierro, aspecto rustico",colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Bar", name:"Vinoteca 24 Botellas",            price:680,  originalPrice:820,  featured:false, isNew:false, sub:null, description:"24 botellas, temperatura doble zona, silencioso",     colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Bar", name:"Mueble Bar Moderno LED",          price:760,  originalPrice:920,  featured:false, isNew:true,  sub:null, description:"Led RGB programable, control remoto, espejado",       colors:["#1a1a18","#c8bfa8"] },
  { categoryId:"Bar", name:"Cantinero Plegable",              price:280,  originalPrice:340,  featured:false, isNew:false, sub:null, description:"Plegable para guardar, ideal eventos y reuniones",    colors:["#8b7355","#1a1a18"] },
  { categoryId:"Bar", name:"Bar Colonial Tallado",            price:980,  originalPrice:1180, featured:false, isNew:false, sub:null, description:"Tallado colonial, madera caoba, espejo central",      colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Bar", name:"Vinoteca Espejada",               price:620,  originalPrice:750,  featured:false, isNew:false, sub:null, description:"Frente espejado, 16 botellas, luz LED interior",      colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Bar", name:"Mueble Bar Industrial",           price:540,  originalPrice:650,  featured:false, isNew:false, sub:null, description:"Tuberias hierro + tableros madera, estilo brewery",   colors:["#1a1a18","#8b7355"] },
  { categoryId:"Bar", name:"Cantinero Rotativo 360",          price:560,  originalPrice:680,  featured:false, isNew:true,  sub:null, description:"Plataforma giratoria 360, facil acceso a botellas",   colors:["#5c3d1e","#c8bfa8"] },
  { categoryId:"Bar", name:"Bar Premium Espejado",            price:1200, originalPrice:null, featured:false, isNew:false, sub:null, description:"Todo espejado, led perimetral, cristaleria incluida", colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Bar", name:"Vinoteca Climatizada XL",         price:1580, originalPrice:1900, featured:false, isNew:false, sub:null, description:"80 botellas, doble temperatura, compuerta sellada",   colors:["#1a1a18","#4a4a4a"] },
  { categoryId:"Bar", name:"Mueble Bar Retractil",            price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Puertas que esconden todo, parece un mueble normal",  colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Bar", name:"Cantinero Oak Premium",           price:720,  originalPrice:860,  featured:false, isNew:false, sub:null, description:"Roble americano, encimera granito negro, elegante",   colors:["#8b7355","#1a1a18"] },
  { categoryId:"Bar", name:"Bar Miniatura Compacto",          price:220,  originalPrice:280,  featured:false, isNew:true,  sub:null, description:"Pequeño y funcional, ideal apartamentos",             colors:["#1a1a18","#c8bfa8"] },

  // ── BUFETERA ──
  { categoryId:"Bufetera", name:"Bufetera Comedor Nogal",     price:680,  originalPrice:820,  featured:true,  isNew:false, sub:null, description:"3 puertas + 3 cajones, encimera marmol blanco",       colors:["#5c3d1e","#c8bfa8"] },
  { categoryId:"Bufetera", name:"Bufetera Vinoteca",          price:540,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Porta 12 botellas + bandeja de servicio",             colors:["#8b7355","#1a1a18"] },
  { categoryId:"Bufetera", name:"Bufetera Colonial",          price:780,  originalPrice:940,  featured:false, isNew:false, sub:null, description:"Estilo colonial, tallado en madera cedro macizo",     colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Bufetera", name:"Bufetera 3 Cajones",         price:460,  originalPrice:560,  featured:false, isNew:false, sub:null, description:"3 cajones anchos, ideal comedor diario",              colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Bufetera", name:"Aparador Buffet XL",         price:840,  originalPrice:1020, featured:true,  isNew:false, sub:null, description:"1.8m de largo, encimera, puertas y cajones",         colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Bufetera", name:"Bufetera Escandinava",       price:520,  originalPrice:630,  featured:false, isNew:false, sub:null, description:"Patas palillo, puertas rejilla, pino escandinavo",    colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Bufetera", name:"Buffet Industrial Metal",    price:480,  originalPrice:580,  featured:false, isNew:false, sub:null, description:"Marco metalico, puertas madera, look industrial",     colors:["#1a1a18","#8b7355"] },
  { categoryId:"Bufetera", name:"Bufetera Moderna Lacada",    price:560,  originalPrice:680,  featured:false, isNew:true,  sub:null, description:"Lacado gris acero, tirador oculto, 4 puertas",        colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Bufetera", name:"Aparador Buffet Rustico",    price:440,  originalPrice:530,  featured:false, isNew:false, sub:null, description:"Madera reciclada, bisagras hierro, aspecto antiguo",  colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Bufetera", name:"Bufetera Marmol y Madera",   price:920,  originalPrice:1100, featured:false, isNew:false, sub:null, description:"Encimera marmol Carrara, puertas madera nogal",       colors:["#d4c5b0","#5c3d1e"] },
  { categoryId:"Bufetera", name:"Buffet Clasico Tallado",     price:680,  originalPrice:820,  featured:false, isNew:false, sub:null, description:"Tallado artesanal, patas cabriole, espejo superior",  colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Bufetera", name:"Bufetera Minimalista",       price:360,  originalPrice:440,  featured:false, isNew:false, sub:null, description:"Lineas rectas, sin tiradores, push-to-open",          colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Bufetera", name:"Aparador Buffet Colonial",   price:760,  originalPrice:920,  featured:false, isNew:false, sub:null, description:"Colonial tallado, madera caoba, herrajes dorados",    colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Bufetera", name:"Bufetera con Espejo",        price:540,  originalPrice:660,  featured:false, isNew:true,  sub:null, description:"Espejo trasero incluido, ideal comedor amplio",       colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"Bufetera", name:"Buffet Premium Gold",        price:1080, originalPrice:1280, featured:false, isNew:false, sub:null, description:"Dorados premium, encimera marmol, patas forjadas",   colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Bufetera", name:"Bufetera Vintage Roble",     price:480,  originalPrice:580,  featured:false, isNew:false, sub:null, description:"Roble envejecido, herrajes vintage, cajones amplios", colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Bufetera", name:"Aparador Buffet Blanco",     price:400,  originalPrice:480,  featured:false, isNew:false, sub:null, description:"Lacado blanco, 4 puertas, lineas modernas",           colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Bufetera", name:"Bufetera Japonesa",          price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Estilo japones, madera clara, patas delgadas",        colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Bufetera", name:"Buffet Madera Cedro",        price:640,  originalPrice:780,  featured:false, isNew:false, sub:null, description:"Cedro aromático, interior forrado, 5 cajones",        colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Bufetera", name:"Bufetera Retro Color",       price:320,  originalPrice:390,  featured:false, isNew:true,  sub:null, description:"Lacado en colores retro, ideal diseño atrevido",      colors:["#4a6741","#d4c5b0"] },

  // ── APARADOR ──
  { categoryId:"Aparador", name:"Aparador Bajo Escandinavo",  price:580,  originalPrice:680,  featured:true,  isNew:false, sub:null, description:"3 puertas, patas oblicuas, lineas limpias nordicas",  colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Aparador", name:"Aparador Alto con Espejo",   price:720,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Espejo de 180cm integrado en puerta lateral",         colors:["#c8bfa8","#8b7355"] },
  { categoryId:"Aparador", name:"Aparador Marmol y Nogal",    price:940,  originalPrice:1120, featured:false, isNew:false, sub:null, description:"Tapa marmol blanco, cajones nogal vaporizado",        colors:["#d4c5b0","#5c3d1e"] },
  { categoryId:"Aparador", name:"Jarron Ceramico Artesanal",  price:145,  originalPrice:null, featured:false, isNew:false, sub:null, description:null,                                                  colors:[] },
  { categoryId:"Aparador", name:"Aparador Colonial Tallado",  price:680,  originalPrice:820,  featured:false, isNew:false, sub:null, description:"Tallado colonial, madera caoba, patas torneadas",     colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Aparador", name:"Aparador Moderno Flotante",  price:480,  originalPrice:580,  featured:false, isNew:false, sub:null, description:"Montado en pared, sin patas, 3 puertas abatibles",    colors:["#d4c5b0","#4a4a4a"] },
  { categoryId:"Aparador", name:"Aparador Vintage Oak",       price:560,  originalPrice:680,  featured:false, isNew:false, sub:null, description:"Roble envejecido, tiradores ceramica, patas pin",     colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Aparador", name:"Aparador Industrial Metal",  price:420,  originalPrice:510,  featured:false, isNew:true,  sub:null, description:"Metal negro + tableros madera, bisagras hierro",      colors:["#1a1a18","#8b7355"] },
  { categoryId:"Aparador", name:"Aparador Premium 3 Puertas", price:780,  originalPrice:null, featured:false, isNew:false, sub:null, description:"3 puertas lacadas, bisagras amortiguadas, cajones",   colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Aparador", name:"Aparador Minimalista",       price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Perfil bajo, tirador continuo, laminado mate gris",   colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Aparador", name:"Aparador Art Deco",          price:640,  originalPrice:780,  featured:true,  isNew:false, sub:null, description:"Marco dorado, puertas acanaladas, marmol encimera",   colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Aparador", name:"Aparador Clasico Madera",    price:520,  originalPrice:630,  featured:false, isNew:false, sub:null, description:"Madera maciza, molduras clasicas, barniz brillante",  colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Aparador", name:"Aparador Rustico Pino",      price:360,  originalPrice:440,  featured:false, isNew:false, sub:null, description:"Pino macizo, bisagras hierro forjado, aspecto rustico",colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Aparador", name:"Aparador Lacado Blanco",     price:460,  originalPrice:560,  featured:false, isNew:false, sub:null, description:"Blanco lacado piano, 4 puertas, sin tiradores",       colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Aparador", name:"Aparador con Vitrina",       price:680,  originalPrice:820,  featured:false, isNew:true,  sub:null, description:"Vitrina vidrio superior + cajones inferiores",        colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Aparador", name:"Aparador Contemporaneo",     price:540,  originalPrice:660,  featured:false, isNew:false, sub:null, description:"Lineas contemporaneas, 2 cajones + 2 puertas",        colors:["#4a4a4a","#c8bfa8"] },
  { categoryId:"Aparador", name:"Aparador Colonial Fino",     price:780,  originalPrice:940,  featured:false, isNew:false, sub:null, description:"Colonial refinado, marqueteria, patas cabriole",      colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Aparador", name:"Aparador Bajo Moderno",      price:340,  originalPrice:420,  featured:false, isNew:false, sub:null, description:"Bajo 45cm, largo 150cm, lacado antracita",            colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"Aparador", name:"Aparador Madera Maciza",     price:860,  originalPrice:1040, featured:true,  isNew:false, sub:null, description:"Madera maciza + encimera cuarzo blanco, premium",     colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Aparador", name:"Aparador Retro Metal",       price:380,  originalPrice:460,  featured:false, isNew:true,  sub:null, description:"Metal patinado, puertas madera recuperada, vintage",  colors:["#1a1a18","#8b7355"] },

  // ── ESCRITORIOS ──
  { categoryId:"Escritorios", name:"Escritorio Ejecutivo Oak",   price:760,  originalPrice:920,  featured:true,  isNew:false, sub:null, description:"180cm, 3 cajones, vuelta con archivador",           colors:["#8b7355","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Gamer RGB",       price:540,  originalPrice:640,  featured:false, isNew:true,  sub:null, description:"Esquinero 160x120, portacables, tira LED",          colors:["#1a1a18","#2c2c2c"] },
  { categoryId:"Escritorios", name:"Escritorio Flotante",        price:220,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Instalacion en pared, plegable, sin patas",         colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Nilo Blanco",     price:380,  originalPrice:450,  featured:false, isNew:false, sub:null, description:"Lacado blanco, 2 cajones + repisa lateral",         colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio L Premium",       price:980,  originalPrice:1180, featured:true,  isNew:false, sub:null, description:"Forma L, 200x160, cajones y archivador",            colors:["#8b7355","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Escandinavo",     price:440,  originalPrice:530,  featured:false, isNew:false, sub:null, description:"Pino claro, patas metalicas, cajones suaves",       colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Industrial",      price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Metal negro + tablon madera recuperada",             colors:["#1a1a18","#8b7355"] },
  { categoryId:"Escritorios", name:"Escritorio Pie Metal",       price:320,  originalPrice:390,  featured:false, isNew:true,  sub:null, description:"Patas metalicas ajustables, tablero MDF roble",     colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Escritorios", name:"Escritorio Madera Solida",   price:640,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Madera maciza de roble, cajones laterales",          colors:["#8b7355","#5c3d1e"] },
  { categoryId:"Escritorios", name:"Escritorio Standup Electrico",price:1280,originalPrice:1520, featured:true,  isNew:false, sub:null, description:"Altura regulable electrica 65-130cm, memoria",      colors:["#1a1a18","#d4c5b0"] },
  { categoryId:"Escritorios", name:"Escritorio Rustico Pino",    price:280,  originalPrice:340,  featured:false, isNew:false, sub:null, description:"Pino macizo, aspecto natural, cajones laterales",    colors:["#d4c5b0","#8b7355"] },
  { categoryId:"Escritorios", name:"Escritorio Blanco Laqueado", price:360,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Lacado blanco mate, amplia superficie de trabajo",   colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"Escritorios", name:"Escritorio Esquinero Max",   price:680,  originalPrice:820,  featured:false, isNew:false, sub:null, description:"Maximo aprovechamiento de esquina, storage",        colors:["#8b7355","#d4c5b0"] },
  { categoryId:"Escritorios", name:"Escritorio Home Office",     price:520,  originalPrice:630,  featured:false, isNew:true,  sub:null, description:"Ideal teletrabajo, bandeja teclado + cajones",      colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Con Cajones",     price:480,  originalPrice:580,  featured:false, isNew:false, sub:null, description:"3 cajones laterales, superficie 140cm, nogal",      colors:["#8b7355","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Nogal Premium",   price:840,  originalPrice:1020, featured:false, isNew:false, sub:null, description:"Nogal americano, cajones con amortiguador total",    colors:["#5c3d1e","#8b7355"] },
  { categoryId:"Escritorios", name:"Escritorio Estudio Juvenil", price:340,  originalPrice:410,  featured:false, isNew:false, sub:null, description:"Juvenil funcional, estante superior integrado",      colors:["#4a6741","#d4c5b0"] },
  { categoryId:"Escritorios", name:"Escritorio de Pared",        price:260,  originalPrice:320,  featured:false, isNew:true,  sub:null, description:"Fijado en pared, plegable, sin ocupar espacio",     colors:["#d4c5b0","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Open Space",      price:460,  originalPrice:560,  featured:false, isNew:false, sub:null, description:"Superficie abierta 160cm, ideal home office",       colors:["#c8bfa8","#1a1a18"] },
  { categoryId:"Escritorios", name:"Escritorio Director Gold",   price:1100, originalPrice:1320, featured:false, isNew:false, sub:null, description:"Cuero en la superficie, cajones con llave, lujo",   colors:["#5c3d1e","#8b7355"] },

  // ── SOFA CAMA ──
  { categoryId:"SofaCama", name:"Sofa Cama Clic-Clac Plus",   price:680,  originalPrice:820,  featured:true,  isNew:false, sub:null, description:"Mecanismo clic-clac, colchon espuma 12cm incluido",   colors:["#8b7355","#4a4a4a"] },
  { categoryId:"SofaCama", name:"Sofa Cama Futon Lounge",     price:490,  originalPrice:null, featured:false, isNew:true,  sub:null, description:"Futon japones reclinable, 3 posiciones",              colors:["#2c2c2c","#c8bfa8"] },
  { categoryId:"SofaCama", name:"Sofa Cama Seccional",        price:980,  originalPrice:1180, featured:false, isNew:false, sub:null, description:"Chaise longue convertible con almacenamiento",        colors:["#d4c5b0","#5c3d1e"] },
  { categoryId:"SofaCama", name:"Sofa Cama Italiano",         price:760,  originalPrice:null, featured:false, isNew:false, sub:null, description:"Mecanismo italiano de apertura rapida 3 seg",         colors:["#1a1a18","#8b7355"] },
  { categoryId:"SofaCama", name:"Sofa Cama 3 Puestos",        price:840,  originalPrice:1020, featured:true,  isNew:false, sub:null, description:"3 puestos de dia, cama 2 plazas de noche",            colors:["#4a4a4a","#c8bfa8"] },
  { categoryId:"SofaCama", name:"Sofa Cama Chaise Longue",    price:920,  originalPrice:1100, featured:false, isNew:false, sub:null, description:"Chaise longue reversible + cama doble oculta",        colors:["#8b7355","#d4c5b0"] },
  { categoryId:"SofaCama", name:"Sofa Cama Futon Japones",    price:380,  originalPrice:460,  featured:false, isNew:true,  sub:null, description:"Futon tradicional, 3 posiciones, lavable",            colors:["#d4c5b0","#4a4a4a"] },
  { categoryId:"SofaCama", name:"Sofa Cama Premium Oslo",     price:1240, originalPrice:1480, featured:true,  isNew:false, sub:null, description:"Tapizado premium, colchon muelles ensacados",         colors:["#c8bfa8","#2c2c2c"] },
  { categoryId:"SofaCama", name:"Sofa Cama Moderno",          price:680,  originalPrice:820,  featured:false, isNew:false, sub:null, description:"Moderno, mecanismo facil, colchon HR incluido",       colors:["#4a4a4a","#d4c5b0"] },
  { categoryId:"SofaCama", name:"Sofa Cama Esquinero",        price:1140, originalPrice:1380, featured:false, isNew:false, sub:null, description:"Esquinero con cama oculta, cajones bajo asiento",     colors:["#8b7355","#1a1a18"] },
  { categoryId:"SofaCama", name:"Sofa Cama Futon XL",         price:540,  originalPrice:660,  featured:false, isNew:true,  sub:null, description:"XL 2.2m cama, futon grueso 12cm, colores variados",   colors:["#d4c5b0","#4a6741"] },
  { categoryId:"SofaCama", name:"Sofa Cama Clasico",          price:560,  originalPrice:680,  featured:false, isNew:false, sub:null, description:"Clasico, resistente, 20 anos de garantia estructura", colors:["#5c3d1e","#c8bfa8"] },
  { categoryId:"SofaCama", name:"Sofa Cama Rustico",          price:480,  originalPrice:580,  featured:false, isNew:false, sub:null, description:"Madera maciza visible, tapizado lino natural",        colors:["#8b7355","#d4c5b0"] },
  { categoryId:"SofaCama", name:"Sofa Cama Tapizado",         price:720,  originalPrice:860,  featured:false, isNew:false, sub:null, description:"Todo tapizado, armado facil, base recta",             colors:["#2c2c2c","#8b7355"] },
  { categoryId:"SofaCama", name:"Sofa Cama Matrimonial",      price:980,  originalPrice:1180, featured:false, isNew:false, sub:null, description:"Cama matrimonial 2.2m x 1.4m al extender",           colors:["#d4c5b0","#4a4a4a"] },
  { categoryId:"SofaCama", name:"Sofa Cama Plegable Easy",    price:380,  originalPrice:460,  featured:false, isNew:false, sub:null, description:"Mecanismo plegable easy-open, 1 movimiento",          colors:["#c8bfa8","#8b7355"] },
  { categoryId:"SofaCama", name:"Sofa Cama Boutique",         price:1080, originalPrice:1280, featured:false, isNew:true,  sub:null, description:"Tapizado boutique hotel, colchon viscoelastico",      colors:["#d4c5b0","#c8bfa8"] },
  { categoryId:"SofaCama", name:"Sofa Cama Infantil",         price:340,  originalPrice:420,  featured:false, isNew:false, sub:null, description:"Pequeno para habitacion infantil, colores vivos",     colors:["#4a6741","#c8bfa8"] },
  { categoryId:"SofaCama", name:"Sofa Cama Ultra Comfort",    price:840,  originalPrice:1020, featured:false, isNew:false, sub:null, description:"Colchon viscoelastico 14cm, el mas comodo del mundo", colors:["#c8bfa8","#d4c5b0"] },
  { categoryId:"SofaCama", name:"Sofa Cama Open Space",       price:640,  originalPrice:780,  featured:false, isNew:false, sub:null, description:"Ideal estudios y lofts, almacenamiento bajo asiento", colors:["#4a4a4a","#8b7355"] },
];

function buildProducts() {
  _imgIdx = 0;
  return ALL_CATALOG.map((p, i) => {
    const img = nextImg();
    return {
      name: p.name,
      description: p.description || null,
      categoryId: p.categoryId,
      category: p.categoryId,
      subcategory: p.sub || null,
      primaryImage: img,
      imageUrl: img,
      price: p.price,
      originalPrice: p.originalPrice || null,
      onSale: p.originalPrice != null,
      isNew: p.isNew || false,
      featured: p.featured || false,
      displayOrder: i,
      colors: p.colors || [],
      gallery: [],
    };
  });
}
export const PRODUCTS = buildProducts();

/* ---------- SETTINGS ---------- */

function buildStoreLocations() {
  const locations = [];

  const raw = {
    ecuador: [
      { city: "Guayaquil", tag: "Flagship", address: "Av. Francisco de Orellana y Justino Cornejo, CC. Policentro, Local 142", hours: "Lun–Sab 9:00–21:00 · Dom 10:00–18:00", phone: "04 268 1234" },
      { city: "Quito Norte", tag: null, address: "Av. Naciones Unidas E3-71 y Shyris, CC. Quicentro Shopping, L2-34", hours: "Lun–Sab 10:00–20:00 · Dom 10:00–17:00", phone: "02 246 5678" },
      { city: "Quito Sur", tag: null, address: "Av. Morán Valverde N65-48 y Rodrigo de Chavez, CC. El Recreo", hours: "Lun–Sab 10:00–20:00 · Dom 11:00–16:00", phone: "02 334 9012" },
      { city: "Cuenca", tag: null, address: "Av. Ordonez Lasso y Carlos Arizaga, CC. Milenium Plaza, L. 88", hours: "Lun–Sab 9:30–19:30 · Dom 10:00–15:00", phone: "07 285 3456" },
      { city: "Ambato", tag: null, address: "Av. Cevallos 1435 y Mera, CC. Caracol, Planta Baja", hours: "Lun–Sab 9:00–19:00", phone: "03 242 7890" },
      { city: "Manta", tag: null, address: "Av. 4 de Noviembre y Calle 24, CC. Paseo Shopping Manta", hours: "Lun–Sab 10:00–20:00 · Dom 10:00–16:00", phone: "05 292 1234" },
    ],
    panama: [
      { city: "Panama City", tag: "Flagship", address: "Via Espana 99, CC. Multiplaza Pacific, Local 2-18", hours: "Lun–Sab 10:00–21:00 · Dom 11:00–19:00", phone: "+507 390 1234" },
      { city: "San Miguelito", tag: null, address: "Av. Ricardo J. Alfaro, CC. Metromall, Local B-24", hours: "Lun–Sab 10:00–20:00", phone: "+507 260 5678" },
      { city: "David", tag: null, address: "Av. Francisco Clark, CC. Chiriqui Mall, Piso 1", hours: "Lun–Sab 10:00–20:00 · Dom 11:00–18:00", phone: "+507 774 3456" },
    ],
    peru: [
      { city: "Lima Miraflores", tag: "Flagship", address: "Av. Larco 1150, CC. Larcomar, Tienda 34", hours: "Lun–Dom 10:00–22:00", phone: "+51 1 445 7890" },
      { city: "Lima San Isidro", tag: null, address: "Calle Las Begonias 475, CC. El Polo, Tienda 18", hours: "Lun–Sab 10:00–21:00 · Dom 11:00–18:00", phone: "+51 1 222 3456" },
      { city: "Arequipa", tag: null, address: "Av. Ejercito 793, CC. Arequipa Center, L. 52", hours: "Lun–Sab 9:30–20:00 · Dom 10:00–16:00", phone: "+51 54 285 678" },
    ],
  };

  for (const [country, stores] of Object.entries(raw)) {
    for (const s of stores) {
      locations.push({
        country,
        city: s.city,
        address: s.address,
        hours: s.hours,
        phone: s.phone,
        isFlagship: s.tag === "Flagship",
      });
    }
  }

  return locations;
}

export const SETTINGS = {
  storeLocations: buildStoreLocations(),

  heroSection: {
    eyebrow: "Coleccion 2025",
    title: "Espacios que hablan de ti",
    description: "Muebles de autor para quienes entienden que cada rincon del hogar es una declaracion de caracter.",
    bgImage: `${CDN}/banners/lifestyle.jpg`,
  },

  promoBanner: {
    title: "Accede a Crédito Directo",
    subtitle: "Divide tus compras hasta en 12 meses sin intereses. Y si prefieres pagar en efectivo, disfruta de hasta 30% de descuento en categorias y productos seleccionados.",
    discountPct: 12,
    discountText: "12 MESES SIN INTERESES",
    ctaText: "Consultar financiamiento",
    image: `${CDN}/banners/dormitorios-hero.jpg`,
  },

  whatsappNumber: "593959667093",
  whatsappPhoneDisplay: "095 966 7093",
  phoneLine: "1800 123 456",
  email: "info@palito.com",

  businessHours: {
    weekdays: "8:00 — 20:00",
    saturday: "9:00 — 18:00",
    sunday: "10:00 — 15:00",
  },

  socialLinks: {
    facebook: "https://facebook.com/muebleriapalito",
    instagram: "https://instagram.com/muebleriapalito",
    youtube: "https://youtube.com/@muebleriapalito",
    whatsapp: "https://wa.me/593959667093?text=ESTOY%20INTERESADO%20EN%20MUEBLERIA%20PALITO%20PARA%20COMPRAR%20UN%20MUEBLE%2C%20ME%20PODRIAN%20ASESORAR%3F%20VENGO%20DE%20LA%20PAGINA",
  },
};

/* ---------- AGGREGATED EXPORT ---------- */

export const CATALOG_DATA = {
  categories: CATEGORIES,
  products: PRODUCTS,
  settings: SETTINGS,
};
